name: ESLint

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: rm package-lock.json
        
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        
    - run: npm i
    - run: npm run lint
