name: ESLint

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
      env:
        RUNNER_TEMP: "/tmp/"
        
    - run: npm ci
    - run: npm run lint
